---
title: "Traffic Analysis"
author: "Manolo Vasquez Mendoza"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

# Introduction
_Hello! I am Manolo Vasquez. I wanted to do a proyect to practice my data analysisa and programming skills. I chose a dataset about US Accidents found in Kaggle (https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents)._

_To begin, let's take a look to our dataset_
```{python}
#IMPORTING
import pandas as pd 
import numpy as np
import sqlite3
from lets_plot import *
import matplotlib.pyplot as plt
LetsPlot.setup_html(isolated_frame=True)
```

```{python}
#lets take a look to the dataset

data_file = "data/US_Accidents_March23.csv"

use_cols = [
    'ID', 'Severity', 'Start_Time', 'State', 'City', 
    'Temperature(F)', 'Visibility(mi)', 'Weather_Condition'
]
df_total = pd.read_csv(data_file, usecols=use_cols, nrows=400000)
df = df_total.sample(frac=0.75, random_state=10)
```

```{python}
# Agregrating useful columns
df["Start_Time"] = pd.to_datetime(df["Start_Time"])

df["Year"] = df["Start_Time"].dt.year
df["Month"] = df["Start_Time"].dt.month
df["Hour"] = df["Start_Time"].dt.hour
df['Month_Name'] = df['Start_Time'].dt.strftime('%B')

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'

df['Season'] = df['Month'].apply(get_season)

df.head()
```

```{python}
#Cleaning NULL
df.isna().sum().sort_values(ascending=False)

df['Temperature(F)'].fillna(df['Temperature(F)'].median(), inplace=True)
df['Visibility(mi)'].fillna(df['Visibility(mi)'].median(), inplace=True)
df['Weather_Condition'].fillna("Unknown", inplace=True)
df = df.dropna(subset="City")

df.shape
```

# Question 1: WHICH ARE THE STATES WITH MORE ACCIDENTS BETWEEN 2016 AND 2017?

_Here we can see that California is clearly the state with the greatest amount of accidents between 2016 and 2017. Almost the 35.6% of the total accidents United States had happened in Califonia! This will be our state of interest for now. Here comes the questions, Why California? What happens in California that does not happen in other states? Maybe is the weather?_
```{python}
#Answering the question
accidents = df.query("2016 <= Year <= 2017")
accidents = accidents.groupby('State').size().reset_index(name='Total')
accidents = accidents.sort_values('Total', ascending= False)
```
```{python}
#Making Graphs
(
  ggplot(accidents, aes(x="Total", y="State"))+
  geom_bar(aes(x="Total",y="State", fill="Total"),stat="identity")+
  labs(
    title="States with most accidents 2016-17"
  )
)
```

```{python}
#How is California in the total USA accidents
plt.figure(figsize=(8,8))
accidents_plot = accidents.set_index('State')['Total']
accidents_plot.plot.pie(autopct='%1.1f%%', startangle=90)
plt.ylabel('')
plt.title('Accident share by state (2016-17)')
plt.show()
```


# Question 2: WHAT IS THE WEATHER MOST OF THE ACCIDENTS OCCUR WITH?

_This does not tell us what we expected. Most of the accidents happened in a clear day for both the entire country and California. So, what is the reason? maybe the hour?_

```{python}
#Prepare Data
weather = df
weather = weather.groupby("Weather_Condition").size().reset_index(name='Total')
weather = weather.sort_values("Total", ascending=False)
weather_ca = df.query("State=='CA'")
weather_ca = weather_ca.groupby("Weather_Condition").size().reset_index(name='Total')
weather_ca = weather_ca.sort_values("Total", ascending=False)
```

### Let's see how is in the entire country
```{python}

(
  ggplot(weather, aes(x="Weather_Condition", y="Total"))+
  geom_bar(aes(x="Weather_Condition",y="Total", fill="Total"),stat="identity")+
  labs(
    title="Most Dangerous Weather USA",
    y="Total Accidents"
  )
)
```

### How is in California
```{python}

(
  ggplot(weather_ca, aes(x="Weather_Condition", y="Total"))+
  geom_bar(aes(x="Weather_Condition",y="Total", fill="Total"),stat="identity")+
  labs(
    title="Most Dangerous Weather Califonia",
    y="Total Accidents"
  )
)
```

# Question 3: WHAT IS THE MOST FREQUENT HOUR ACCIDENTS OCCUR?

_Here is interesting. Most of the accidents happen between 8am-12pm reprensenting 28.2% of the nation accidents, when most of the youth are studying and adults are working. Having in mind that most of them happen in a clear day there should be another reason. However, this belief of accidents happen because of weather, the ineptitude of youth at driving or late hours is false. It is obvious that they are related and we must take care of being aware of the weather, being well educated at driving and don't driving sleepy. However, there should be something more that makes most of the people to have accidents in a clear day in the middle of the morning._
```{python}
#Preparing the data
hour = df
hour_ca = df.query("State =='CA'")

bins = list(range(0, 25, 2))
labels = [f"{i:02d}-{i+2:02d}" for i in range(0, 24, 2)]

hour['Hour_Group'] = pd.cut(hour['Hour'], bins=bins, labels=labels, right=False)
hour_ca['Hour_Group'] = pd.cut(hour_ca['Hour'], bins=bins, labels=labels, right=False)

hour = hour.groupby("Hour_Group").size().reset_index(name='Total')
hour_ca = hour_ca.groupby("Hour_Group").size().reset_index(name='Total')
```

### How is in USA
```{python}

(
  ggplot(hour, aes(x="Hour_Group", y="Total"))+
  geom_point()+
  labs(
    title="Hours When Accidents Occur USA",
    x="Time Frame",
    y="Total Accidents"
  )
)
```
```{python}
plt.figure(figsize=(8,8))
hour_plot = hour.set_index('Hour_Group')['Total']
hour_plot.plot.pie(autopct='%1.1f%%', startangle=90)
plt.ylabel('')
plt.title('Accidents in USA per HOUR')
plt.show()
```

### How is in California
```{python}

(
  ggplot(hour_ca, aes(x="Hour_Group", y="Total"))+
  geom_point()+
  labs(
    title="Hours When Accidents Occur California",
    x="Time Frame",
    y="Total Accidents"
  )
)
```

```{python}
plt.figure(figsize=(8,8))
hourca_plot = hour_ca.set_index('Hour_Group')['Total']
hourca_plot.plot.pie(autopct='%1.1f%%', startangle=90)
plt.ylabel('')
plt.title('Accidents in California per HOUR')
plt.show()
```

_Finally, let's change the look and see if the accidents are related to a specific month. Probably December(Christmas) or November(Black Friday) makes people take questionable decisions at driving. Probably the season._

# Question 4: WHAT IS THE MONTH WHEN MOST OF THE ACCIDENT HAPPEN?

_Seems that finally we got a middle answer. Summer and fall are the months when most of the accidents happen. Seems that is because of the high temperatures as shown in the second graph. Probably wheels tend to explote in highways, or the shine blinds the driver which makes sense that most of the accidents happens in the middle of the morning in a clear day._
```{python}
month = df.groupby(["Month", "Month_Name"]).size().reset_index(name="Total")
month = month.sort_values("Month").drop(columns="Month")

```

```{python}
(
  ggplot(month, aes(x="Month_Name", y="Total"))+
  geom_line()+
  geom_vline(xintercept=2, linetype=5,color="green")+
  geom_text(x=2.5, y=15000, label="Spring", color="black",angle = 90)+
  geom_vline(xintercept=5, linetype=5,color="yellow")+
  geom_text(x=5.5, y=15000, label="Summer", color="black",angle = 90)+
  geom_vline(xintercept=8, linetype=5,color="orange")+
  geom_text(x=8.5, y=15000, label="Fall", color="black",angle = 90)+
  geom_vline(xintercept=11, linetype=5,color="blue")+
  geom_text(x=11.5, y=15000, label="Winter", color="black",angle = 90)+
  labs(
    title="Accidents per Month",
    x="Month",
    y="Total Accidents"
  )  
)
```

## Is the temperatures of the season related?
```{python}
temperature = (
  df.groupby("Season")["Temperature(F)"]
  .median()
  .reset_index(name="Median_Temperature(F)")
  .sort_values("Median_Temperature(F)",ascending=False)
)

```

```{python}
(
  ggplot(temperature, aes(x="Season", y="Median_Temperature(F)"))+
  geom_bar(aes(x="Season", y="Median_Temperature(F)",fill="Median_Temperature(F)"),stat="identity")
)
```